In [1]:
#https://chrisalbon.com/machine-learning/cross_validation_parameter_tuning_grid_search.html

In [2]:
import numpy as np
from sklearn.grid_search import GridSearchCV
from sklearn import datasets, svm
#from sklearn.svm import SVC
import matplotlib.pyplot as plt
import time
print ("libraries loaded.")
#start_time = time.time()
#print("--- %s seconds ---" % (time.time() - start_time))

D:\DProgramFiles\python3Anaconda\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
D:\DProgramFiles\python3Anaconda\lib\site-packages\sklearn\grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


libraries loaded.


In [3]:
# Load the digit data
digits = datasets.load_digits()
#https://kite.com/docs/python/sklearn.datasets.base.Bunch
print (type(digits))

<class 'sklearn.datasets.base.Bunch'>


In [4]:
# View the features of the first observation
digits.data[0:1]

array([[  0.,   0.,   5.,  13.,   9.,   1.,   0.,   0.,   0.,   0.,  13.,
         15.,  10.,  15.,   5.,   0.,   0.,   3.,  15.,   2.,   0.,  11.,
          8.,   0.,   0.,   4.,  12.,   0.,   0.,   8.,   8.,   0.,   0.,
          5.,   8.,   0.,   0.,   9.,   8.,   0.,   0.,   4.,  11.,   0.,
          1.,  12.,   7.,   0.,   0.,   2.,  14.,   5.,  10.,  12.,   0.,
          0.,   0.,   0.,   6.,  13.,  10.,   0.,   0.,   0.]])

In [5]:
# View the target of the first observation
digits.target[0:1]

array([0])

In [6]:
# Create dataset 1
data1_features = digits.data[:1000]
data1_target = digits.target[:1000]
print ("type(data1_features):", type(data1_features), data1_features.shape)
print ("type(data1_target):", type(data1_target), data1_target.shape)

# Create dataset 2
data2_features = digits.data[1000:]
data2_target = digits.target[1000:]
print ("type(data2_features):", type(data2_features), data2_features.shape)
print ("type(data2_target):", type(data2_target), data2_target.shape)


type(data1_features): <class 'numpy.ndarray'> (1000, 64)
type(data1_target): <class 'numpy.ndarray'> (1000,)
type(data2_features): <class 'numpy.ndarray'> (797, 64)
type(data2_target): <class 'numpy.ndarray'> (797,)


In [7]:
parameter_candidates = [
  {'C': [1, 10, 100, 1000], 'kernel': ['linear']},
  {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel': ['rbf']},
]
print (type(parameter_candidates), type(parameter_candidates[0]))

<class 'list'> <class 'dict'>


In [8]:
# Create a classifier object with the classifier and parameter candidates
start_time = time.time()
clf = GridSearchCV(estimator=svm.SVC(), param_grid=parameter_candidates, n_jobs=-1)
print("--- %s seconds to Create SVC classifier object ---" % (time.time() - start_time))

# Train the classifier on data1's feature and target data
start_time = time.time()
print (clf.fit(data1_features, data1_target))
print("--- %s seconds to train the classifier on data1 ---" % (time.time() - start_time))

--- 0.0 seconds to Create SVC classifier object ---
GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params={}, iid=True, n_jobs=-1,
       param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']}, {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel': ['rbf']}],
       pre_dispatch='2*n_jobs', refit=True, scoring=None, verbose=0)
--- 1.5883338451385498 seconds to train the classifier on data1 ---


In [9]:
# View the accuracy score
print('Best score for data1:', clf.best_score_) 

Best score for data1: 0.942


In [10]:
# View the best parameters for the model found using grid search
print('Best C:',clf.best_estimator_.C) 
print('Best Kernel:',clf.best_estimator_.kernel)
print('Best Gamma:',clf.best_estimator_.gamma)
#http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html

Best C: 10
Best Kernel: rbf
Best Gamma: 0.001


In [11]:
# Apply the classifier trained using data1 to data2, and view the accuracy score
clf.score(data2_features, data2_target)  

0.96988707653701378

In [26]:
# Train a new classifier using the best parameters found by the grid search
clfNew = svm.SVC(C=10, kernel='rbf', gamma=0.001)
clfNew.fit(data1_features, data1_target)
clfNew.score(data2_features, data2_target)


0.96988707653701378

In [22]:
print (type(clfNew))

<class 'sklearn.svm.classes.SVC'>


In [25]:
start_time = time.time()
data2_target_predicted = clfNew.predict(data2_features)
print("--- %s seconds to predict ---" % (time.time() - start_time))
print(data2_target_predicted[0:10])
print(data2_target[0:10])

--- 0.05116891860961914 seconds to predict ---
[1 4 0 5 3 6 9 6 1 7]
[1 4 0 5 3 6 9 6 1 7]
